#+TITLE: Arquitectura Técnica del Proyecto de Portal cantv.com.ve en TIL
#+AUTHOR:    Cooperativa Venezolana de Tecnologías Libres R.S.
#+EMAIL:     info@covetel.com.ve
#+DATE:
#+DESCRIPTION: Documentación corporativa de la arquitectura técnica del proyecto de portales web en Plone para el sitio cantv.com.ve,
#+KEYWORDS: covetel cantv portal
#+LaTeX_CLASS: covetel
#+LaTeX_CLASS_OPTIONS: [letterpaper,oneside,spanish]
#+LANGUAGE:  es
#+OPTIONS:   H:3 num:t toc:3 \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:
#+LINK_HOME:
#+LATEX_HEADER: \usepackage{array}
#+LATEX_HEADER: \input{titulo-arq-tecnica-proyecto-portales}

* Introducción

* Objeto y campo de aplicación

* Requerimientos técnicos de Arquitectura

** Análisis técnico del modelo funcional de la solución propuesta

*** Alcance de la solución

*** Necesidad de sustituir sistemas existentes

*** Necesidad de migración de datos desde la plataforma actual hacia la nueva implementación 

*** Necesidad de instalación de nuevos productos de Tecnologías de Información

*** Necesidad de implementar nuevas interfaces en los sistemas corporativos existentes para intercambiar información con la solución propuesta

*** Necesidad de intercambio de información síncrona y asíncrona entre la solución propuesta y los sistemas corporativos existentes

*** Necesidad de ejecutar procesos por lotes en los sistemas corporativos existentes que sirvan de insumo a la solución propuesta y viceversa

*** Necesidad de emitir reportes directamente desde la solución propuesta

** Sistemas corporativos involucrados

*** Sistemas a sustituir

*** Sistemas a incorporar

*** Sistemas impactados

*** Sistemas relacionados

*** Diagnóstico de la necesidad de entornos operativos de los sistemas corporativos involucrados en la construcción de la solución propuesta

*** Diagnóstico de la necesidad de autorizaciones en los sistemas corporativos involucrados en la construcción de la solución propuesta

** Conceptualización de acceso al servicio desde el usuario final

* Requerimientos de configuración de los nuevos productos propuestos para la implementación

** Nuevos productos a implementar en la solución

** Protocolo de autenticación y autorización de los productos a los que se conectarán los usuarios finales

** Factibilidad de transposición de objetos programáticos

** Factibilidad de registros de trazas de operación en la aplicación

* Análisis técnico de los procesos TI requeridos

** Tecnología de Intercambio en línea y en lote de los productos en donde debe ocurrir el intercambio

** Tecnología de Ejecución de Procesos en Lote

** Tecnología de Ejecución de Reportes, Indicadores y Alertas

** Tecnología de Supervisión de Procesos

** Tecnología de Ejecución y Analisis de Trazas.

** Diagnóstico de la necesidad de entornos operativos para la construcción de los servicios, procesos en lote y reportes requeridos como parte de la solución

* Arquitectura Técnica TI

** Estrategia de Acceso (Autenticación, Autorización y Auditoria)

*** Autenticación 

Plone posee una base datos de usuario propia, pero se recomienda utilizar un
repositorio de usuarios externo, como un servidor compatible con la tecnología
de LDAP.
\\

LDAP (Lightweight Directory Access Protocol) es un protocolo estándar para
acceso y modificación de datos usando servicios de directorio que operan sobre
el protocolo TCP/IP. 
\\

Existen varias implementaciones del protocolo LDAP, tales como /Microsoft
Active Directory/, /Novell/, /Sun One/, /OpenLDAP/.
\\

Nuestro equipo recomienda el uso de /OpenLDAP/ como /backend/ de
autenticación de usuarios. /OpenLDAP/ es un proyecto de Software Libre que
implementa el protocolo /LDAP/.
\\

Actualmente CANTV posee una plataforma de servicios de directorios basada en
/OpenLDAP/, en donde ya se encuentran los usuarios corporativos de la empresa,
recomendamos utilizar esta plataforma.

*** =plone.app.ldap=

Existe un componente de Plone llamado =plone.app.ldap=, este componente provee
un panel de control para manejar los usuarios y grupos que se encuentran en la
plataforma de directorio /LDAP/ al que este conectado.

Este compomente provee las funcionalidades desarrolladas por el módulo
=PloneLDAP= [fn:1] y está construido usando las librerías =LDAPMultiPlugins=
[fn:2] y =LDAPUserFolder= [fn:2].

Este componente integra el /backend/ LDAP a Plone de la siguiente manera: 

 1. Los usuarios en la base de datos LDAP pueden ser usados como usuarios normales
    de Plone, se puede buscar entre los usuarios, asignar roles, crear
    usuarios y eliminar usuarios. [fn:3]
 2. Los grupos en la base de datos LDAP pueden ser usados como grupos normales
    de Plone. se puede verlos, manejar los miembros de un grupo, crear nuevos
    grupos, remover los grupos. Es importante destacar que los grupos /LDAP/
    solo pueden tener como miembros a usuarios /LDAP/, los usuarios /LDAP/
    pueden ser miembros de grupos internos de Plone que no están en /LDAP/.
 3. Las propiedades de pertenencia a grupos de los usuarios LDAP no necesitan
    guardarse completamente en el directorio LDAP, pude combinar propiedades
    almacenadas en LDAP con propiedades almacenadas en ZODB.

Nota: Si usa Active Directory como backend de este componente, todo el acceso
es de solo lectura, no podrá escribir o modificar entradas en el directorio.

** Estrategia de Entornos Operativos
** Dimensionamiento de la Plataforma Tecnológica 
** Definición de Estrategia de Transposición entre los Entornos Operativos
** Definición de Estrategia de Incorporación de Nuevas Funcionalidades. (desarrollos)
** Definición de Estrategia de Manejo de Trazas, Reportes, Indicadores y Alertas

* Definición Estrategias de Configuración Técnica de la Plataforma TI

** Estrategia Adecuación Técnica de Entornos Operativos
** Estrategia Administración Técnica de Entornos Operativos
** Estrategia Certificación Técnica de la Plataforma
** Estrategia de Servicio y Soporte

[fn:1] [[http://plone.org/products/ploneldap/][PloneLDAP]]
[fn:2] [[http://www.dataflake.org/software/ldapmultiplugins/][LDAPMultiPlugins]]
[fn:3] Se recomienda configurar el componente para que no se puedan crear ni eliminar usuarios, ya que estos son funciones de otras gerencias.
